name: dummy_workflow

on:
  workflow_call:
    inputs:
      executor_dir:
        required: false
        type: string
        default: "."

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo executor_dir ${{ inputs.executor_dir }}
          echo executor_dir default ${{ inputs.executor_dir.default }}
          echo executor_dir required ${{ inputs.executor_dir.required }}
