name: test

on:
  push:
    branches:
      - main
    inputs:
      executor_dir:
        required: false
        type: string
        default: "."


jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "executor_dir: ${{ github.event.inputs.executor_dir }}"